
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgcclgezwkfedkkmrtsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnY2NsZ2V6d2tmZWRra21ydHNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMTA5NTYsImV4cCI6MjA1Nzg4Njk1Nn0.cuwxebz48CWSCx143ogMgj1Q0qe1nB8Ut3yg86F7XWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
